apiVersion: v1
kind: Pod
metadata:
  name: mounterdeamon
spec:
  restartPolicy: Never
  volumes:
    - name: test-volume
      hostPath:
      # directory location on host
        path: /media
  containers:
  - name: mounterbusybox
    image: busybox
    args:
      - 'sleep'
      - '89700'
    securityContext:
      privileged: true
    volumeMounts: 
      - mountPath: /media
        name: test-volume
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir -p /media/shared && mount -t cifs //lagrippacstest.file.core.windows.net/sharedstorage  /media/shared -o vers=3.0,username=lagrippacstest,password='S0bQUBM+zROLMrCG/+OhbVncPsOcqo+WJ0Qta6S2HmEyLds2ICmtfem97CtgSLT3VLUYB7vyEfcgzsik5wUnbQ==',dir_mode=0777,file_mode=0777,mfsymlinks > /tmp/mount.log"]
      preStop:
        exec:
          command: ["/bin/sh","-c","umount /media/shared"]



